#!/bin/bash

BASE_LOAD_PATH=$1
BASE_SAVE_PATH=$2
STEP_SIZE=$3
START=$4
END=$5
TARGET_TP_SIZE=$6
TARGET_EP_SIZE=$7
TARGET_PP_SIZE=$8

qsub -v RTYPE=rt_HF,BASE_LOAD_PATH=${BASE_LOAD_PATH},BASE_SAVE_PATH=${BASE_SAVE_PATH},START_ITER=${START},END_ITER=${END},STEP_SIZE=${STEP_SIZE},TARGET_TP_SIZE=${TARGET_TP_SIZE},TARGET_EP_SIZE=${TARGET_EP_SIZE},TARGET_PP_SIZE=${TARGET_PP_SIZE} convert.sh
