common:
  v3_0_info_root: "/home/shared/corpus/llm-jp-corpus/v3.0.0/training_resharded_tokenize_ver3.0/token_info"

datasets:
  ja_cc1:
    basedir: "v3_0_info_root"
    file: "2024_0410_ja.sakura_home.csv"
    filter: 
      - train/ja/cc-1
    repeat: 0.8996
  ja_wiki:
    basedir: "v3_0_info_root"
    file: "2024_0410_ja.sakura_home.csv"
    filter: 
      - train/ja/wiki
    repeat: 2