num_nodes: 2
devices: 8
accelerator: gpu
precision: bf16-mixed

sft:
    max_epochs: 2
    max_steps: -1

    val_check_interval: 50
    save_interval: ${.val_check_interval}

    limit_val_batches: 1.0
    gradient_clip_val: 1.0

# do not change these
logger: False # logger provided by exp_manager
enable_checkpointing: False
use_distributed_sampler: False
max_time: null

max_epochs: ${.sft.max_epochs}
max_steps: ${.sft.max_steps}
