common:
  v3_0_info_root: "/home/shared/corpus/llm-jp-corpus/v3.0.0/training_resharded_tokenize_ver3.0/token_info"

datasets:
  code:
    basedir: "v3_0_info_root"
    file: "2024_0410_code.sakura_home.csv"
    repeat: 0.1014
  en:
    basedir: "v3_0_info_root"
    file: "2024_0410_en.sakura_home.csv"
    repeat: 0.1014
  ja_kaken-:
    basedir: "v3_0_info_root"
    file: "2024_0410_ja.sakura_home.csv"
    filter: 
      - train/ja/kaken
      - train/ja/warp-html
    repeat: 2
  ja_warp_pdfe0:
    basedir: "v3_0_info_root"
    file: "2024_0410_ja.sakura_home.csv"
    filter: 
      - train/ja/warp-pdf-e00
    repeat: 0.8222
  ja_warp_pdfe2:
    basedir: "v3_0_info_root"
    file: "2024_0410_ja.sakura_home.csv"
    filter: 
      - train/ja/warp-pdf-e02
    repeat: 0.4111