offline_inference:
  prompt_json_path: ["<<OFFLINE_OUT>>/<<MODEL_NORM>>/*.eval-prompt.json"]
  output_base_dir: <<OFFLINE_OUT>>

model:
  _target_: "vllm.LLM"
  model: <<MODEL>>
  dtype: "bfloat16"  # ["bfloat16", "float16", "float32"]
  gpu_memory_utilization: 0.9

tokenizer:
  _target_: "transformers.AutoTokenizer.from_pretrained"
  pretrained_model_name_or_path: <<TOKENIZER>>
  trust_remote_code: false
  use_fast: true

pipeline_kwargs:
  add_special_tokens: false

generator_kwargs:
  _target_: "vllm.SamplingParams"
  # top_p: 1.0
  # top_k: 0
  temperature: 0.0
  repetition_penalty: 1.0
