#!/usr/bin/env python3

import argparse
import ast
import concurrent.futures
import gzip
import inspect
import json
import queue
import shlex
import subprocess
import sys
import threading
import time
from collections import deque
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace
from typing import Any


# The global variables for Megatron-LM imports are populated by configure_megatron_imports().
torch: Any = None
BlendedMegatronDatasetBuilder: Any = None
build_tokenizer: Any = None
GPTDataset: Any = None
GPTDatasetConfig: Any = None


@dataclass(frozen=True)
class ReadTimings:
    getitem_seconds: float = 0.0
    token_ids_seconds: float = 0.0
    spans_seconds: float = 0.0
    record_seconds: float = 0.0


@dataclass(frozen=True)
class TimedPayload:
    payload: dict[str, Any]
    timings: ReadTimings


CONFIG_ENV_NAMES = (
    "MEGATRON_PATH",
    "GLOBAL_BATCH_SIZE",
    "TRAIN_STEPS",
    "SEQ_LENGTH",
    "SEED",
    "SPLIT",
    "TOKENIZER_TYPE",
    "TOKENIZER_MODEL",
    "MAKE_VOCAB_SIZE_DIVISIBLE_BY",
    "VOCAB_EXTRA_IDS",
    "DATA_PATH",
    "DATA_CACHE_PATH",
)

MEGATRON_DEFAULT_OPTIONS = {
    "--global-batch-size": "global_batch_size",
    "--train-iters": "train_iters",
    "--seq-length": "seq_length",
    "--seed": "seed",
    "--split": "split",
    "--tokenizer-type": "tokenizer_type",
    "--make-vocab-size-divisible-by": "make_vocab_size_divisible_by",
    "--vocab-extra-ids": "vocab_extra_ids",
    "--data-cache-path": "data_cache_path",
    "--no-mmap-bin-files": "mmap_bin_files",
}

SCRIPT_DEFAULTS = {
    "output": "outputs/global-batches.jsonl.gz",
    "output_queue_size": 256,
    "gzip_compresslevel": 9,
    "progress": True,
    "progress_interval": 5.0,
    "include_text": False,
    "reader_workers": 8,
    "compress_workers": 4,
    "compress_chunk_records": 256,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Replay Megatron pretraining global batches on CPU without initializing "
            "distributed training or loading a model. Activate the Python virtual "
            "environment for Megatron-LM before running this script."
        )
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help=(
            "Shell config file generated by extract_replay_config.py. Explicit "
            "CLI arguments override values from this file."
        ),
    )
    parser.add_argument(
        "--megatron-path",
        type=str,
        default=None,
        help="Path to the Megatron-LM repository to import.",
    )
    parser.add_argument(
        "--iter-index",
        type=int,
        default=None,
        help=(
            "Replay only this training iteration/global batch index. This is "
            "a shorthand for --iter-start INDEX --iter-end INDEX+1."
        ),
    )
    parser.add_argument(
        "--iter-start",
        type=int,
        default=None,
        help=(
            "First training iteration/global batch index to replay, inclusive."
        ),
    )
    parser.add_argument(
        "--iter-end",
        type=int,
        default=None,
        help=(
            "Training iteration end, exclusive. Defaults to the end of the "
            "training loop when --iter-start is set."
        ),
    )
    parser.add_argument("--global-batch-size", type=int, default=None)
    parser.add_argument(
        "--train-iters",
        type=int,
        default=None,
        help="Set this to the value used when the reference dump was generated.",
    )
    parser.add_argument("--seq-length", type=int, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--split", type=str, default=None)
    parser.add_argument("--tokenizer-type", type=str, default=None)
    parser.add_argument("--tokenizer-model", type=str, default=None, help="Path to the tokenizer model file, e.g., a SentencePiece model.")
    parser.add_argument("--make-vocab-size-divisible-by", type=int, default=None)
    parser.add_argument("--vocab-extra-ids", type=int, default=None)
    parser.add_argument("--data-path", nargs="*", default=None, help="One or more dataset paths or weight-path pairs for blended training.")
    parser.add_argument("--data-cache-path", type=str, default=None)
    parser.add_argument("--mmap-bin-files", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Write gzip-compressed JSONL output to this .jsonl.gz path.",
    )
    parser.add_argument(
        "--output-queue-size",
        type=int,
        default=None,
        help=(
            "Number of records to buffer between dataset reading and JSONL gzip "
            "writing. Use 0 to disable pipelined writing."
        ),
    )
    parser.add_argument(
        "--gzip-compresslevel",
        type=int,
        default=None,
        choices=range(0, 10),
        metavar="{0..9}",
        help="gzip compression level for --output. Lower is faster; default preserves gzip's level 9.",
    )
    parser.add_argument(
        "--progress",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Show output progress on stderr.",
    )
    parser.add_argument(
        "--progress-interval",
        type=float,
        default=None,
        help="Minimum seconds between progress updates.",
    )
    parser.add_argument(
        "--include-text",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Include detokenized text in each output record. Disabled by default.",
    )
    parser.add_argument(
        "--reader-workers",
        type=int,
        default=None,
        help=(
            "Number of reader threads used to fetch dataset records and build "
            "output payloads. Defaults to 8."
        ),
    )
    parser.add_argument(
        "--compress-workers",
        type=int,
        default=None,
        help=(
            "Number of worker threads used to JSON-serialize and gzip-compress "
            "JSONL chunks. Values greater than 1 write concatenated gzip members. "
            "Defaults to 4."
        ),
    )
    parser.add_argument(
        "--compress-chunk-records",
        type=int,
        default=None,
        help="Number of records per gzip member when --compress-workers is greater than 1.",
    )
    args = parser.parse_args()
    apply_config_and_defaults(args, parser)
    return args


def read_shell_config(config_path: str) -> dict[str, str]:
    resolved = Path(config_path).expanduser().resolve()
    if not resolved.is_file():
        raise FileNotFoundError(f"--config does not exist: {resolved}")

    script = "\n".join(
        [
            "set -euo pipefail",
            f"source {shlex.quote(str(resolved))}",
            *[
                f"printf '%s\\0%s\\0' {shlex.quote(name)} \"${{{name}:-}}\""
                for name in CONFIG_ENV_NAMES
            ],
        ]
    )
    completed = subprocess.run(
        ["bash", "-c", script],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    parts = [part.decode("utf-8") for part in completed.stdout.split(b"\0")]
    return {
        parts[index]: parts[index + 1]
        for index in range(0, len(parts) - 1, 2)
        if parts[index + 1]
    }


def get_megatron_arg_defaults(megatron_path: str) -> dict[str, Any]:
    arguments_path = (
        Path(megatron_path).expanduser().resolve() / "megatron" / "training" / "arguments.py"
    )
    if not arguments_path.is_file():
        raise FileNotFoundError(
            f"cannot read Megatron-LM argument defaults: {arguments_path}"
        )

    tree = ast.parse(arguments_path.read_text(encoding="utf-8"), filename=str(arguments_path))
    defaults: dict[str, Any] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Attribute) or node.func.attr != "add_argument":
            continue

        option_names = [
            arg.value
            for arg in node.args
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str)
        ]
        matched_options = [
            option_name
            for option_name in option_names
            if option_name in MEGATRON_DEFAULT_OPTIONS
        ]
        if not matched_options:
            continue

        keyword_by_name = {keyword.arg: keyword.value for keyword in node.keywords}
        if "default" in keyword_by_name:
            default_value = ast.literal_eval(keyword_by_name["default"])
        else:
            action_node = keyword_by_name.get("action")
            action = (
                action_node.value
                if isinstance(action_node, ast.Constant)
                and isinstance(action_node.value, str)
                else None
            )
            if action == "store_false":
                default_value = True
            elif action == "store_true":
                default_value = False
            else:
                default_value = None

        for option_name in matched_options:
            defaults[MEGATRON_DEFAULT_OPTIONS[option_name]] = default_value

    return defaults


def apply_config_and_defaults(
    args: argparse.Namespace,
    parser: argparse.ArgumentParser,
) -> None:
    config = read_shell_config(args.config) if args.config else {}
    env_to_attr = {
        "MEGATRON_PATH": ("megatron_path", str),
        "GLOBAL_BATCH_SIZE": ("global_batch_size", int),
        "TRAIN_STEPS": ("train_iters", int),
        "SEQ_LENGTH": ("seq_length", int),
        "SEED": ("seed", int),
        "SPLIT": ("split", str),
        "TOKENIZER_TYPE": ("tokenizer_type", str),
        "TOKENIZER_MODEL": ("tokenizer_model", str),
        "MAKE_VOCAB_SIZE_DIVISIBLE_BY": ("make_vocab_size_divisible_by", int),
        "VOCAB_EXTRA_IDS": ("vocab_extra_ids", int),
        "DATA_CACHE_PATH": ("data_cache_path", str),
    }
    for env_name, (attr_name, converter) in env_to_attr.items():
        if getattr(args, attr_name) is None and env_name in config:
            setattr(args, attr_name, converter(config[env_name]))
    if args.data_path is None and "DATA_PATH" in config:
        args.data_path = shlex.split(config["DATA_PATH"])

    megatron_defaults = {}
    if args.megatron_path is not None:
        megatron_defaults = get_megatron_arg_defaults(args.megatron_path)
    for attr_name, default_value in megatron_defaults.items():
        if default_value is not None and getattr(args, attr_name) is None:
            setattr(args, attr_name, default_value)

    if args.split is None and args.data_path is not None:
        # Match Megatron-LM's effective legacy default in validate_args().
        args.split = "969, 30, 1"

    for attr_name, default_value in SCRIPT_DEFAULTS.items():
        if getattr(args, attr_name) is None:
            setattr(args, attr_name, default_value)

    missing = []
    for attr_name, option_name in (
        ("megatron_path", "--megatron-path"),
        ("global_batch_size", "--global-batch-size"),
        ("train_iters", "--train-iters"),
        ("seq_length", "--seq-length"),
        ("seed", "--seed"),
        ("split", "--split"),
        ("tokenizer_type", "--tokenizer-type"),
        ("tokenizer_model", "--tokenizer-model"),
        ("data_path", "--data-path"),
    ):
        if getattr(args, attr_name) in (None, []):
            missing.append(option_name)
    if missing:
        parser.error(
            "missing required arguments after applying --config: "
            + ", ".join(missing)
        )


def configure_megatron_imports(megatron_path: str) -> None:
    global torch
    global BlendedMegatronDatasetBuilder
    global build_tokenizer
    global GPTDataset
    global GPTDatasetConfig

    resolved = Path(megatron_path).expanduser().resolve()
    if not resolved.is_dir():
        raise FileNotFoundError(f"--megatron-path does not exist: {resolved}")
    if not (resolved / "megatron").is_dir():
        raise FileNotFoundError(
            f"--megatron-path must point to a Megatron-LM repository: {resolved}"
        )

    resolved_str = str(resolved)
    if resolved_str not in sys.path:
        sys.path.insert(0, resolved_str)

    try:
        import torch as imported_torch
        from megatron.core.datasets.blended_megatron_dataset_builder import (
            BlendedMegatronDatasetBuilder as ImportedBlendedMegatronDatasetBuilder,
        )
        from megatron.core.datasets.gpt_dataset import (
            GPTDataset as ImportedGPTDataset,
            GPTDatasetConfig as ImportedGPTDatasetConfig,
        )
        from megatron.training.tokenizer import build_tokenizer as imported_build_tokenizer
    except ImportError as exc:
        raise ImportError(
            "Failed to import Megatron-LM modules. Make sure the Python virtual "
            "environment for Megatron-LM is activated before running this script."
        ) from exc

    torch = imported_torch
    BlendedMegatronDatasetBuilder = ImportedBlendedMegatronDatasetBuilder
    build_tokenizer = imported_build_tokenizer
    GPTDataset = ImportedGPTDataset
    GPTDatasetConfig = ImportedGPTDatasetConfig


@contextmanager
def rank_zero_when_distributed_is_not_initialized():
    if torch.distributed.is_initialized():
        yield
        return

    original_get_rank = torch.distributed.get_rank
    torch.distributed.get_rank = lambda *args, **kwargs: 0
    try:
        yield
    finally:
        torch.distributed.get_rank = original_get_rank


def build_tokenizer_for_replay(args: argparse.Namespace):
    tokenizer_args = SimpleNamespace(
        rank=0,
        tokenizer_type=args.tokenizer_type,
        tokenizer_model=args.tokenizer_model,
        vocab_file=None,
        merge_file=None,
        vocab_size=None,
        vocab_extra_ids=args.vocab_extra_ids,
        make_vocab_size_divisible_by=args.make_vocab_size_divisible_by,
        tensor_model_parallel_size=1,
        padded_vocab_size=None,
    )
    return build_tokenizer(tokenizer_args)


def get_iteration_range(args: argparse.Namespace) -> range:
    if args.iter_index is not None:
        if args.iter_index < 0:
            raise ValueError("--iter-index must be non-negative")
        start = args.iter_index
        end = args.iter_index + 1
    else:
        start = 0 if args.iter_start is None else args.iter_start
        end = args.train_iters if args.iter_end is None else args.iter_end

    if start < 0:
        raise ValueError("--iter-start must be non-negative")
    if end < start:
        raise ValueError("--iter-end must be greater than or equal to --iter-start")
    if end > args.train_iters:
        raise IndexError(
            f"requested iteration range exceeds training loop: end={end}, "
            f"total={args.train_iters}"
        )
    return range(start, end)


def get_blend_from_data_path(data_path: list[str]):
    if len(data_path) == 1:
        return [data_path[0]], None

    if len(data_path) % 2 != 0:
        raise ValueError(
            "--data-path must be either a single dataset path or weight-path pairs"
        )

    weights = []
    prefixes = []
    for weight_index in range(0, len(data_path), 2):
        weights.append(float(data_path[weight_index]))
        prefixes.append(data_path[weight_index + 1])
    return prefixes, weights


def build_train_dataset(args: argparse.Namespace):
    tokenizer = build_tokenizer_for_replay(args)
    config_kwargs = {
        "random_seed": args.seed,
        "sequence_length": args.seq_length,
        "blend": get_blend_from_data_path(args.data_path),
        "blend_per_split": [None, None, None],
        "split": args.split,
        "path_to_cache": args.data_cache_path,
        "mmap_bin_files": args.mmap_bin_files,
        "mock": False,
        "tokenizer": tokenizer,
        "reset_position_ids": False,
        "reset_attention_mask": False,
        "eod_mask_loss": False,
        "create_attention_mask": True,
    }
    accepted_config_kwargs = inspect.signature(GPTDatasetConfig).parameters
    config = GPTDatasetConfig(
        **{
            key: value
            for key, value in config_kwargs.items()
            if key in accepted_config_kwargs
        }
    )
    train_num_samples = args.train_iters * args.global_batch_size
    sizes = [train_num_samples, 0, 0]
    with rank_zero_when_distributed_is_not_initialized():
        train_ds, _, _ = BlendedMegatronDatasetBuilder(
            GPTDataset,
            sizes,
            lambda: True,
            config,
        ).build()
    if train_ds is None:
        raise RuntimeError("failed to build the train dataset")
    return train_ds, tokenizer


def get_dataset_paths_from_data_path(data_path: list[str]) -> list[str]:
    if len(data_path) == 1:
        return data_path

    if len(data_path) % 2 != 0:
        raise ValueError(
            "--data-path must be either a single dataset path or weight-path pairs"
        )

    dataset_paths = []
    for weight_index in range(0, len(data_path), 2):
        float(data_path[weight_index])
        dataset_paths.append(data_path[weight_index + 1])
    return dataset_paths


def get_global_batch_dataset_indices(
    args: argparse.Namespace,
    total_samples: int,
    iteration: int,
) -> list[int]:
    batch_start = iteration * args.global_batch_size
    if batch_start >= total_samples:
        raise IndexError(
            f"requested global batch exceeds dataset length: start={batch_start}, total={total_samples}"
        )
    batch_end = min(batch_start + args.global_batch_size, total_samples)
    return list(range(batch_start, batch_end))


def resolve_source_dataset_sample(
    dataset: Any,
    dataset_index: int,
    item: dict[str, Any],
) -> tuple[Any, int, int | None]:
    if hasattr(dataset, "datasets"):
        dataset_id = int(item.get("dataset_id", dataset.dataset_index[dataset_index]))
        dataset_sample_index = int(
            item.get("dataset_sample_index", dataset.dataset_sample_index[dataset_index])
        )
        return dataset.datasets[dataset_id], dataset_sample_index, dataset_id

    return dataset, dataset_index, None


def get_indexed_dataset_spans(
    source_dataset: Any,
    dataset_sample_index: int,
) -> list[dict[str, int]]:
    if not all(
        hasattr(source_dataset, attr)
        for attr in ("document_index", "sample_index", "shuffle_index", "dataset")
    ):
        return []

    shuffled_sample_index = int(source_dataset.shuffle_index[dataset_sample_index])
    doc_index_beg, doc_index_beg_offset = source_dataset.sample_index[shuffled_sample_index]
    doc_index_end, doc_index_end_offset = source_dataset.sample_index[shuffled_sample_index + 1]

    spans = []
    for doc_index in range(int(doc_index_beg), int(doc_index_end) + 1):
        document_id = int(source_dataset.document_index[doc_index])
        offset = 0 if doc_index > doc_index_beg else int(doc_index_beg_offset)
        if doc_index < doc_index_end:
            length = int(source_dataset.dataset.sequence_lengths[document_id]) - offset
        else:
            length = int(doc_index_end_offset) - offset + 1

        spans.append(
            {
                "document_id": document_id,
                "offset": offset,
                "length": length,
            }
        )

    return spans


def build_sample_record(
    args: argparse.Namespace,
    dataset: Any,
    dataset_index: int,
    iteration: int,
    item: dict[str, Any],
    tokenizer: Any,
    dataset_paths: list[str],
    token_ids: list[int],
) -> tuple[dict[str, Any], float, float]:
    record_started_at = time.perf_counter()
    record = {
        "iteration": iteration,
        "token_ids": token_ids,
    }
    if args.include_text:
        record["text"] = tokenizer.detokenize(token_ids)
    record["dataset_id"] = int(item.get("dataset_id", 0))
    if record["dataset_id"] < len(dataset_paths):
        record["dataset_path"] = dataset_paths[record["dataset_id"]]
    source_dataset, source_sample_index, _source_dataset_id = resolve_source_dataset_sample(
        dataset,
        dataset_index,
        item,
    )
    spans_started_at = time.perf_counter()
    indexed_dataset_spans = get_indexed_dataset_spans(source_dataset, source_sample_index)
    spans_seconds = time.perf_counter() - spans_started_at
    record["indexed_dataset_spans"] = indexed_dataset_spans
    if "dataset_path" not in record and hasattr(source_dataset, "dataset_path"):
        record["dataset_path"] = source_dataset.dataset_path
    record_seconds = time.perf_counter() - record_started_at - spans_seconds
    return record, spans_seconds, record_seconds


def build_sample_record_from_index(
    args: argparse.Namespace,
    dataset: Any,
    tokenizer: Any,
    dataset_paths: list[str],
    iteration: int,
    dataset_index: int,
) -> TimedPayload:
    getitem_started_at = time.perf_counter()
    item = dataset[dataset_index]
    getitem_seconds = time.perf_counter() - getitem_started_at

    token_ids_started_at = time.perf_counter()
    token_ids = item["tokens"].tolist() + [int(item["labels"][-1])]
    token_ids_seconds = time.perf_counter() - token_ids_started_at

    record, spans_seconds, record_seconds = build_sample_record(
        args,
        dataset,
        dataset_index,
        iteration,
        item,
        tokenizer,
        dataset_paths,
        token_ids,
    )
    return TimedPayload(
        payload=record,
        timings=ReadTimings(
            getitem_seconds=getitem_seconds,
            token_ids_seconds=token_ids_seconds,
            spans_seconds=spans_seconds,
            record_seconds=record_seconds,
        ),
    )


def iter_iteration_dataset_indices(args: argparse.Namespace, dataset_length: int):
    for iteration in get_iteration_range(args):
        for dataset_index in get_global_batch_dataset_indices(
            args,
            dataset_length,
            iteration,
        ):
            yield iteration, dataset_index


def iter_global_batch_records(
    args: argparse.Namespace,
    dataset: Any,
    tokenizer: Any,
    dataset_paths: list[str],
    iteration: int,
):
    dataset_indices = get_global_batch_dataset_indices(args, len(dataset), iteration)
    for dataset_index in dataset_indices:
        yield build_sample_record_from_index(
            args, dataset, tokenizer, dataset_paths, iteration, dataset_index
        )


def iter_output_payloads_parallel(
    args: argparse.Namespace,
    dataset: Any,
    tokenizer: Any,
    dataset_paths: list[str],
):
    reader_workers = max(1, args.reader_workers)
    if reader_workers == 1:
        for iteration in get_iteration_range(args):
            yield from iter_global_batch_records(
                args,
                dataset,
                tokenizer,
                dataset_paths,
                iteration,
            )
        return

    work_items = iter(iter_iteration_dataset_indices(args, len(dataset)))
    max_pending = reader_workers * 2
    pending: deque[concurrent.futures.Future[TimedPayload]] = deque()

    def submit_next(executor: concurrent.futures.ThreadPoolExecutor) -> bool:
        try:
            iteration, dataset_index = next(work_items)
        except StopIteration:
            return False
        pending.append(
            executor.submit(
                build_sample_record_from_index,
                args,
                dataset,
                tokenizer,
                dataset_paths,
                iteration,
                dataset_index,
            )
        )
        return True

    with concurrent.futures.ThreadPoolExecutor(
        max_workers=reader_workers,
        thread_name_prefix="replay-reader",
    ) as executor:
        for _ in range(max_pending):
            if not submit_next(executor):
                break

        while pending:
            future = pending.popleft()
            yield future.result()
            submit_next(executor)


def iter_output_payloads(args: argparse.Namespace):
    dataset, tokenizer = build_train_dataset(args)
    dataset_paths = get_dataset_paths_from_data_path(args.data_path)
    yield from iter_output_payloads_parallel(args, dataset, tokenizer, dataset_paths)


class ProgressReporter:
    def __init__(self, total: int | None, interval_seconds: float, enabled: bool) -> None:
        self.enabled = enabled
        self.interval_seconds = interval_seconds
        self.last_postfix_at = 0.0
        self.bar = None
        if self.enabled:
            try:
                from tqdm import tqdm
            except ImportError as exc:
                raise RuntimeError(
                    "tqdm is required for progress reporting; install tqdm or pass --no-progress"
                ) from exc
            self.bar = tqdm(
                total=total,
                desc="replay",
                unit="records",
                mininterval=interval_seconds,
                file=sys.stderr,
            )

    def update(self, increment: int = 1, stats: "PerformanceStats | None" = None) -> None:
        if self.bar is not None:
            if stats is not None:
                now = time.monotonic()
                if now - self.last_postfix_at >= self.interval_seconds:
                    self.bar.set_postfix_str(stats.format_for_progress(), refresh=False)
                    self.last_postfix_at = now
            self.bar.update(increment)

    def finish(self) -> None:
        if self.bar is not None:
            self.bar.close()


class PerformanceStats:
    def __init__(self, queue_max_size: int | None = None) -> None:
        self.lock = threading.Lock()
        self.queue_size: int | None = None
        self.queue_max_size = queue_max_size
        self.reader_count = 0
        self.reader_seconds = 0.0
        self.getitem_count = 0
        self.getitem_seconds = 0.0
        self.token_ids_count = 0
        self.token_ids_seconds = 0.0
        self.spans_count = 0
        self.spans_seconds = 0.0
        self.record_count = 0
        self.record_seconds = 0.0
        self.put_wait_count = 0
        self.put_wait_seconds = 0.0
        self.get_wait_count = 0
        self.get_wait_seconds = 0.0
        self.json_count = 0
        self.json_seconds = 0.0
        self.gzip_count = 0
        self.gzip_seconds = 0.0
        self.write_count = 0
        self.write_seconds = 0.0

    def set_queue_size(self, value: int | None) -> None:
        with self.lock:
            self.queue_size = value

    def add_reader(self, seconds: float) -> None:
        with self.lock:
            self.reader_count += 1
            self.reader_seconds += seconds

    def add_read_timings(self, timings: ReadTimings, count: int = 1) -> None:
        with self.lock:
            self.getitem_count += count
            self.getitem_seconds += timings.getitem_seconds
            self.token_ids_count += count
            self.token_ids_seconds += timings.token_ids_seconds
            self.spans_count += count
            self.spans_seconds += timings.spans_seconds
            self.record_count += count
            self.record_seconds += timings.record_seconds

    def add_put_wait(self, seconds: float) -> None:
        with self.lock:
            self.put_wait_count += 1
            self.put_wait_seconds += seconds

    def add_get_wait(self, seconds: float) -> None:
        with self.lock:
            self.get_wait_count += 1
            self.get_wait_seconds += seconds

    def add_json(self, seconds: float, count: int = 1) -> None:
        with self.lock:
            self.json_count += count
            self.json_seconds += seconds

    def add_gzip(self, seconds: float, count: int = 1) -> None:
        with self.lock:
            self.gzip_count += count
            self.gzip_seconds += seconds

    def add_write(self, seconds: float, count: int = 1) -> None:
        with self.lock:
            self.write_count += count
            self.write_seconds += seconds

    @staticmethod
    def _average_ms(total_seconds: float, count: int) -> float:
        if count == 0:
            return 0.0
        return 1000.0 * total_seconds / count

    def format_for_progress(self) -> str:
        with self.lock:
            queue_size = self.queue_size
            queue_max_size = self.queue_max_size
            reader_ms = self._average_ms(self.reader_seconds, self.reader_count)
            getitem_ms = self._average_ms(self.getitem_seconds, self.getitem_count)
            token_ids_ms = self._average_ms(
                self.token_ids_seconds, self.token_ids_count
            )
            spans_ms = self._average_ms(self.spans_seconds, self.spans_count)
            record_ms = self._average_ms(self.record_seconds, self.record_count)
            put_wait_ms = self._average_ms(self.put_wait_seconds, self.put_wait_count)
            get_wait_ms = self._average_ms(self.get_wait_seconds, self.get_wait_count)
            json_ms = self._average_ms(self.json_seconds, self.json_count)
            gzip_ms = self._average_ms(self.gzip_seconds, self.gzip_count)
            write_ms = self._average_ms(self.write_seconds, self.write_count)

        if queue_size is None:
            queue_text = "q=-"
        elif queue_max_size:
            queue_text = f"q={queue_size}/{queue_max_size}"
        else:
            queue_text = f"q={queue_size}"
        return (
            f"{queue_text} "
            f"read={reader_ms:.1f}ms "
            f"getitem={getitem_ms:.1f}ms "
            f"tok={token_ids_ms:.1f}ms "
            f"spans={spans_ms:.1f}ms "
            f"record={record_ms:.1f}ms "
            f"put={put_wait_ms:.1f}ms "
            f"get={get_wait_ms:.1f}ms "
            f"json={json_ms:.1f}ms "
            f"gzip={gzip_ms:.1f}ms "
            f"write={write_ms:.1f}ms"
        )


def get_expected_output_records(args: argparse.Namespace) -> int:
    return len(get_iteration_range(args)) * args.global_batch_size


def resolve_output_path(output_path: str) -> Path:
    resolved = Path(output_path)
    if resolved.suffixes[-2:] != [".jsonl", ".gz"]:
        raise ValueError(f"--output must end with .jsonl.gz: {output_path}")
    if not resolved.is_absolute():
        resolved = (Path.cwd() / resolved).resolve()
    resolved.parent.mkdir(parents=True, exist_ok=True)
    return resolved


def unwrap_timed_payload(item: Any, stats: PerformanceStats) -> dict[str, Any]:
    if isinstance(item, TimedPayload):
        stats.add_read_timings(item.timings)
        return item.payload
    return item


def write_output_serial(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    progress: ProgressReporter,
    stats: PerformanceStats,
) -> None:
    resolved = resolve_output_path(output_path)
    payload_iter = iter(payloads)
    with gzip.open(
        resolved,
        "wt",
        encoding="utf-8",
        compresslevel=gzip_compresslevel,
    ) as writer:
        while True:
            read_started_at = time.perf_counter()
            try:
                payload_item = next(payload_iter)
            except StopIteration:
                break
            stats.add_reader(time.perf_counter() - read_started_at)
            payload = unwrap_timed_payload(payload_item, stats)

            json_started_at = time.perf_counter()
            line = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
            stats.add_json(time.perf_counter() - json_started_at)

            write_started_at = time.perf_counter()
            writer.write(line)
            writer.write("\n")
            stats.add_write(time.perf_counter() - write_started_at)
            progress.update(stats=stats)
    progress.finish()


def write_output_pipelined(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    output_queue_size: int,
    progress: ProgressReporter,
    stats: PerformanceStats,
) -> None:
    resolved = resolve_output_path(output_path)
    sentinel = object()
    output_queue: queue.Queue[Any] = queue.Queue(maxsize=output_queue_size)
    writer_errors: list[BaseException] = []
    writer_failed = threading.Event()

    def writer_thread_main() -> None:
        try:
            with gzip.open(
                resolved,
                "wt",
                encoding="utf-8",
                compresslevel=gzip_compresslevel,
            ) as writer:
                while True:
                    get_started_at = time.perf_counter()
                    payload_item = output_queue.get()
                    stats.add_get_wait(time.perf_counter() - get_started_at)
                    stats.set_queue_size(output_queue.qsize())
                    try:
                        if payload_item is sentinel:
                            return
                        payload = unwrap_timed_payload(payload_item, stats)
                        json_started_at = time.perf_counter()
                        line = json.dumps(
                            payload,
                            ensure_ascii=False,
                            separators=(",", ":"),
                        )
                        stats.add_json(time.perf_counter() - json_started_at)

                        write_started_at = time.perf_counter()
                        writer.write(line)
                        writer.write("\n")
                        stats.add_write(time.perf_counter() - write_started_at)
                        progress.update(stats=stats)
                    finally:
                        output_queue.task_done()
        except BaseException as exc:
            writer_errors.append(exc)
            writer_failed.set()

    writer_thread = threading.Thread(
        target=writer_thread_main,
        name="replay-output-writer",
        daemon=True,
    )
    writer_thread.start()

    try:
        payload_iter = iter(payloads)
        while True:
            if writer_failed.is_set():
                raise writer_errors[0]
            read_started_at = time.perf_counter()
            try:
                payload = next(payload_iter)
            except StopIteration:
                break
            stats.add_reader(time.perf_counter() - read_started_at)
            while True:
                if writer_failed.is_set():
                    raise writer_errors[0]
                try:
                    put_started_at = time.perf_counter()
                    output_queue.put(payload, timeout=0.1)
                    stats.add_put_wait(time.perf_counter() - put_started_at)
                    stats.set_queue_size(output_queue.qsize())
                    break
                except queue.Full:
                    stats.add_put_wait(time.perf_counter() - put_started_at)
                    stats.set_queue_size(output_queue.qsize())
                    continue
    finally:
        while True:
            try:
                output_queue.put(sentinel, timeout=0.1)
                break
            except queue.Full:
                if writer_failed.is_set():
                    break
        writer_thread.join()

    if writer_errors:
        raise writer_errors[0]
    progress.finish()


def encode_jsonl_gzip_member(
    payloads: list[dict[str, Any]],
    gzip_compresslevel: int,
) -> tuple[bytes, int, float, float]:
    json_started_at = time.perf_counter()
    jsonl = bytearray()
    for payload in payloads:
        jsonl.extend(
            json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        )
        jsonl.append(10)
    json_seconds = time.perf_counter() - json_started_at

    gzip_started_at = time.perf_counter()
    compressed = gzip.compress(bytes(jsonl), compresslevel=gzip_compresslevel)
    gzip_seconds = time.perf_counter() - gzip_started_at
    return compressed, len(payloads), json_seconds, gzip_seconds


def iter_payload_chunks(
    payloads: Any,
    compress_chunk_records: int,
    stats: PerformanceStats,
):
    payload_iter = iter(payloads)
    while True:
        chunk = []
        while len(chunk) < compress_chunk_records:
            read_started_at = time.perf_counter()
            try:
                payload_item = next(payload_iter)
            except StopIteration:
                if chunk:
                    yield chunk
                return
            stats.add_reader(time.perf_counter() - read_started_at)
            payload = unwrap_timed_payload(payload_item, stats)
            chunk.append(payload)
        yield chunk


def write_output_parallel_compressed(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    compress_workers: int,
    compress_chunk_records: int,
    progress: ProgressReporter,
    stats: PerformanceStats,
) -> None:
    resolved = resolve_output_path(output_path)
    max_pending_chunks = max(1, compress_workers * 2)
    pending: deque[concurrent.futures.Future[tuple[bytes, int, float, float]]] = deque()
    chunks = iter(iter_payload_chunks(payloads, compress_chunk_records, stats))

    def submit_next(executor: concurrent.futures.ThreadPoolExecutor) -> bool:
        try:
            chunk = next(chunks)
        except StopIteration:
            return False
        pending.append(
            executor.submit(encode_jsonl_gzip_member, chunk, gzip_compresslevel)
        )
        stats.set_queue_size(len(pending))
        return True

    with resolved.open("wb") as writer:
        with concurrent.futures.ThreadPoolExecutor(
            max_workers=compress_workers,
            thread_name_prefix="replay-compressor",
        ) as executor:
            for _ in range(max_pending_chunks):
                if not submit_next(executor):
                    break

            while pending:
                future = pending.popleft()
                compressed, record_count, json_seconds, gzip_seconds = future.result()
                stats.add_json(json_seconds, record_count)
                stats.add_gzip(gzip_seconds, record_count)

                write_started_at = time.perf_counter()
                writer.write(compressed)
                stats.add_write(time.perf_counter() - write_started_at, record_count)
                progress.update(record_count, stats=stats)
                submit_next(executor)

    progress.finish()


def write_output(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    output_queue_size: int,
    compress_workers: int,
    compress_chunk_records: int,
    progress: ProgressReporter,
) -> None:
    compress_workers = max(1, compress_workers)
    compress_chunk_records = max(1, compress_chunk_records)
    stats = PerformanceStats(queue_max_size=None)
    if compress_workers > 1:
        stats.queue_max_size = compress_workers * 2
        write_output_parallel_compressed(
            payloads,
            output_path,
            gzip_compresslevel,
            compress_workers,
            compress_chunk_records,
            progress,
            stats,
        )
        return

    stats.queue_max_size = output_queue_size if output_queue_size > 0 else None
    if output_queue_size <= 0:
        write_output_serial(payloads, output_path, gzip_compresslevel, progress, stats)
        return
    write_output_pipelined(
        payloads,
        output_path,
        gzip_compresslevel,
        output_queue_size,
        progress,
        stats,
    )


def main() -> None:
    args = parse_args()
    configure_megatron_imports(args.megatron_path)
    progress = ProgressReporter(
        total=get_expected_output_records(args),
        interval_seconds=args.progress_interval,
        enabled=args.progress,
    )
    write_output(
        iter_output_payloads(args),
        args.output,
        args.gzip_compresslevel,
        args.output_queue_size,
        args.compress_workers,
        args.compress_chunk_records,
        progress,
    )


if __name__ == "__main__":
    main()
