#!/bin/bash
# Node-level training batch replay launcher.
#
# Environment variables:
# * ENV_DIR: Directory that contains scripts/environment.sh, venv, and src/Megatron-LM.
# * REPLAY_CONFIG: Optional shell config generated by extract_replay_config.py.

set -eu -o pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPLAY_CONFIG=${REPLAY_CONFIG:-}
if [[ -n "${REPLAY_CONFIG}" ]]; then
  source "${REPLAY_CONFIG}"
fi
ENV_DIR=${ENV_DIR:-$(pwd)}

source "${ENV_DIR}/scripts/environment.sh"
source "${ENV_DIR}/venv/bin/activate"

export LOGLEVEL=${LOGLEVEL:-INFO}
export PYTHONFAULTHANDLER=${PYTHONFAULTHANDLER:-1}

# Training data range to replay. Defaults to the whole training loop.
ITER_INDEX=${ITER_INDEX:-}
ITER_START=${ITER_START:-}
ITER_END=${ITER_END:-}

# Training config from environment/example/train.sh.
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-1024}
LR_WARMUP_STEPS=${LR_WARMUP_STEPS:-1000}
LR_DECAY_ITERS=${LR_DECAY_ITERS:-5000}
TRAIN_STEPS=${TRAIN_STEPS:-$((${LR_WARMUP_STEPS} + ${LR_DECAY_ITERS}))}
SEQ_LENGTH=${SEQ_LENGTH:-2048}
SEED=${SEED:-1234}

# Data config.
SPLIT=${SPLIT:-1,0,0}
TOKENIZER_TYPE=${TOKENIZER_TYPE:-Llama2Tokenizer}
TOKENIZER_MODEL=${TOKENIZER_MODEL:-src/llm-jp-tokenizer/models/ver3.0/llm-jp-tokenizer-100k.ver3.0b1.model}
MAKE_VOCAB_SIZE_DIVISIBLE_BY=${MAKE_VOCAB_SIZE_DIVISIBLE_BY:-128}
VOCAB_EXTRA_IDS=${VOCAB_EXTRA_IDS:-0}
DATA_PATH=${DATA_PATH:-"2563804308 /data/llm-jp-corpus/v3.0.0/training_resharded_tokenize_ver3.0/train/ja/wiki_0000.jsonl_text_document 1826105478 /data/llm-jp-corpus/v3.0.0/training_resharded_tokenize_ver3.0/train/ja/kaken_0000.jsonl_text_document"}
DATA_CACHE_PATH=${DATA_CACHE_PATH:-cache}
OUTPUT=${OUTPUT:-outputs/global-batches.jsonl.gz}
OUTPUT_QUEUE_SIZE=${OUTPUT_QUEUE_SIZE:-256}
GZIP_COMPRESSLEVEL=${GZIP_COMPRESSLEVEL:-9}
PROGRESS=${PROGRESS:-1}
PROGRESS_INTERVAL=${PROGRESS_INTERVAL:-5}
MEGATRON_PATH=${MEGATRON_PATH:-src/Megatron-LM}

mkdir -p "$(dirname "${OUTPUT}")"

ITER_RANGE_ARGS=()
if [[ -n "${ITER_INDEX}" ]]; then
  ITER_RANGE_ARGS=(--iter-index "${ITER_INDEX}")
else
  if [[ -n "${ITER_START}" ]]; then
    ITER_RANGE_ARGS+=(--iter-start "${ITER_START}")
  fi
  if [[ -n "${ITER_END}" ]]; then
    ITER_RANGE_ARGS+=(--iter-end "${ITER_END}")
  fi
fi

CONFIG_ARGS=()
if [[ -n "${REPLAY_CONFIG}" ]]; then
  CONFIG_ARGS=(--config "${REPLAY_CONFIG}")
fi

PROGRESS_ARGS=(--progress)
if [[ "${PROGRESS}" == "0" || "${PROGRESS}" == "false" || "${PROGRESS}" == "False" ]]; then
  PROGRESS_ARGS=(--no-progress)
fi

EXTRA_REPLAY_ARGS=()
if [[ -n "${EXTRA_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  EXTRA_REPLAY_ARGS=(${EXTRA_ARGS})
fi

# shellcheck disable=SC2206
DATA_PATH_ARGS=(${DATA_PATH})

python "${SCRIPT_DIR}/replay_training_batch.py" \
  "${CONFIG_ARGS[@]}" \
  --megatron-path "${MEGATRON_PATH}" \
  "${ITER_RANGE_ARGS[@]}" \
  --global-batch-size "${GLOBAL_BATCH_SIZE}" \
  --train-iters "${TRAIN_STEPS}" \
  --seq-length "${SEQ_LENGTH}" \
  --seed "${SEED}" \
  --tokenizer-type "${TOKENIZER_TYPE}" \
  --tokenizer-model "${TOKENIZER_MODEL}" \
  --make-vocab-size-divisible-by "${MAKE_VOCAB_SIZE_DIVISIBLE_BY}" \
  --vocab-extra-ids "${VOCAB_EXTRA_IDS}" \
  --data-path "${DATA_PATH_ARGS[@]}" \
  --data-cache-path "${DATA_CACHE_PATH}" \
  --split "${SPLIT}" \
  --output "${OUTPUT}" \
  --output-queue-size "${OUTPUT_QUEUE_SIZE}" \
  --gzip-compresslevel "${GZIP_COMPRESSLEVEL}" \
  "${PROGRESS_ARGS[@]}" \
  --progress-interval "${PROGRESS_INTERVAL}" \
  "${EXTRA_REPLAY_ARGS[@]}"

echo "Wrote replayed batch to ${OUTPUT}"
