#!/usr/bin/env python3

import argparse
import gzip
import inspect
import json
import queue
import shlex
import subprocess
import sys
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from types import SimpleNamespace
from typing import Any


# The global variables for Megatron-LM imports are populated by configure_megatron_imports().
numpy: Any = None
torch: Any = None
BlendedMegatronDatasetBuilder: Any = None
build_tokenizer: Any = None
GPTDataset: Any = None
GPTDatasetConfig: Any = None
Split: Any = None


CONFIG_ENV_NAMES = (
    "MEGATRON_PATH",
    "GLOBAL_BATCH_SIZE",
    "TRAIN_STEPS",
    "SEQ_LENGTH",
    "SEED",
    "SPLIT",
    "TOKENIZER_TYPE",
    "TOKENIZER_MODEL",
    "MAKE_VOCAB_SIZE_DIVISIBLE_BY",
    "VOCAB_EXTRA_IDS",
    "DATA_PATH",
    "DATA_CACHE_PATH",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Replay Megatron pretraining global batches on CPU without initializing "
            "distributed training or loading a model. Activate the Python virtual "
            "environment for Megatron-LM before running this script."
        )
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help=(
            "Shell config file generated by extract_replay_config.py. Explicit "
            "CLI arguments override values from this file."
        ),
    )
    parser.add_argument(
        "--megatron-path",
        type=str,
        default=None,
        help="Path to the Megatron-LM repository to import.",
    )
    parser.add_argument(
        "--iter-index",
        type=int,
        default=None,
        help=(
            "Replay only this training iteration/global batch index. This is "
            "a shorthand for --iter-start INDEX --iter-end INDEX+1."
        ),
    )
    parser.add_argument(
        "--iter-start",
        type=int,
        default=None,
        help=(
            "First training iteration/global batch index to replay, inclusive."
        ),
    )
    parser.add_argument(
        "--iter-end",
        type=int,
        default=None,
        help=(
            "Training iteration end, exclusive. Defaults to the end of the "
            "training loop when --iter-start is set."
        ),
    )
    parser.add_argument("--global-batch-size", type=int, default=None)
    parser.add_argument(
        "--train-iters",
        type=int,
        default=None,
        help="Set this to the value used when the reference dump was generated.",
    )
    parser.add_argument("--seq-length", type=int, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--split", type=str, default=None)
    parser.add_argument("--tokenizer-type", type=str, default=None)
    parser.add_argument("--tokenizer-model", type=str, default=None, help="Path to the tokenizer model file, e.g., a SentencePiece model.")
    parser.add_argument("--make-vocab-size-divisible-by", type=int, default=None)
    parser.add_argument("--vocab-extra-ids", type=int, default=None)
    parser.add_argument("--data-path", nargs="*", default=None, help="One or more dataset paths or weight-path pairs for blended training.")
    parser.add_argument("--data-cache-path", type=str, default=None)
    parser.add_argument("--mmap-bin-files", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Write gzip-compressed JSONL output to this .jsonl.gz path.",
    )
    parser.add_argument(
        "--output-queue-size",
        type=int,
        default=None,
        help=(
            "Number of records to buffer between dataset reading and JSONL gzip "
            "writing. Use 0 to disable pipelined writing."
        ),
    )
    parser.add_argument(
        "--gzip-compresslevel",
        type=int,
        default=None,
        choices=range(0, 10),
        metavar="{0..9}",
        help="gzip compression level for --output. Lower is faster; default preserves gzip's level 9.",
    )
    parser.add_argument(
        "--progress",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Show output progress on stderr.",
    )
    parser.add_argument(
        "--progress-interval",
        type=float,
        default=None,
        help="Minimum seconds between progress updates.",
    )
    args = parser.parse_args()
    apply_config_and_defaults(args, parser)
    return args


def read_shell_config(config_path: str) -> dict[str, str]:
    resolved = Path(config_path).expanduser().resolve()
    if not resolved.is_file():
        raise FileNotFoundError(f"--config does not exist: {resolved}")

    script = "\n".join(
        [
            "set -euo pipefail",
            f"source {shlex.quote(str(resolved))}",
            *[
                f"printf '%s\\0%s\\0' {shlex.quote(name)} \"${{{name}:-}}\""
                for name in CONFIG_ENV_NAMES
            ],
        ]
    )
    completed = subprocess.run(
        ["bash", "-c", script],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    parts = [part.decode("utf-8") for part in completed.stdout.split(b"\0")]
    return {
        parts[index]: parts[index + 1]
        for index in range(0, len(parts) - 1, 2)
        if parts[index + 1]
    }


def apply_config_and_defaults(
    args: argparse.Namespace,
    parser: argparse.ArgumentParser,
) -> None:
    config = read_shell_config(args.config) if args.config else {}
    env_to_attr = {
        "MEGATRON_PATH": ("megatron_path", str),
        "GLOBAL_BATCH_SIZE": ("global_batch_size", int),
        "TRAIN_STEPS": ("train_iters", int),
        "SEQ_LENGTH": ("seq_length", int),
        "SEED": ("seed", int),
        "SPLIT": ("split", str),
        "TOKENIZER_TYPE": ("tokenizer_type", str),
        "TOKENIZER_MODEL": ("tokenizer_model", str),
        "MAKE_VOCAB_SIZE_DIVISIBLE_BY": ("make_vocab_size_divisible_by", int),
        "VOCAB_EXTRA_IDS": ("vocab_extra_ids", int),
        "DATA_CACHE_PATH": ("data_cache_path", str),
    }
    for env_name, (attr_name, converter) in env_to_attr.items():
        if getattr(args, attr_name) is None and env_name in config:
            setattr(args, attr_name, converter(config[env_name]))
    if args.data_path is None and "DATA_PATH" in config:
        args.data_path = shlex.split(config["DATA_PATH"])

    defaults = {
        "global_batch_size": 1024,
        "train_iters": 6000,
        "seq_length": 2048,
        "seed": 1234,
        "split": "1,0,0",
        "tokenizer_type": "Llama2Tokenizer",
        "make_vocab_size_divisible_by": 128,
        "vocab_extra_ids": 0,
        "data_cache_path": "./cache",
        "mmap_bin_files": True,
        "output": "outputs/global-batches.jsonl.gz",
        "output_queue_size": 256,
        "gzip_compresslevel": 9,
        "progress": True,
        "progress_interval": 5.0,
    }
    for attr_name, default_value in defaults.items():
        if getattr(args, attr_name) is None:
            setattr(args, attr_name, default_value)

    missing = []
    for attr_name, option_name in (
        ("megatron_path", "--megatron-path"),
        ("tokenizer_model", "--tokenizer-model"),
        ("data_path", "--data-path"),
    ):
        if getattr(args, attr_name) in (None, []):
            missing.append(option_name)
    if missing:
        parser.error(
            "missing required arguments after applying --config: "
            + ", ".join(missing)
        )


def configure_megatron_imports(megatron_path: str) -> None:
    global numpy
    global torch
    global BlendedMegatronDatasetBuilder
    global build_tokenizer
    global GPTDataset
    global GPTDatasetConfig
    global Split

    resolved = Path(megatron_path).expanduser().resolve()
    if not resolved.is_dir():
        raise FileNotFoundError(f"--megatron-path does not exist: {resolved}")
    if not (resolved / "megatron").is_dir():
        raise FileNotFoundError(
            f"--megatron-path must point to a Megatron-LM repository: {resolved}"
        )

    resolved_str = str(resolved)
    if resolved_str not in sys.path:
        sys.path.insert(0, resolved_str)

    try:
        import numpy as imported_numpy
        import torch as imported_torch
        from megatron.core.datasets.blended_megatron_dataset_builder import (
            BlendedMegatronDatasetBuilder as ImportedBlendedMegatronDatasetBuilder,
        )
        from megatron.core.datasets.gpt_dataset import (
            GPTDataset as ImportedGPTDataset,
            GPTDatasetConfig as ImportedGPTDatasetConfig,
        )
        from megatron.core.datasets.utils import Split as ImportedSplit
        from megatron.training.tokenizer import build_tokenizer as imported_build_tokenizer
    except ImportError as exc:
        raise ImportError(
            "Failed to import Megatron-LM modules. Make sure the Python virtual "
            "environment for Megatron-LM is activated before running this script."
        ) from exc

    numpy = imported_numpy
    torch = imported_torch
    BlendedMegatronDatasetBuilder = ImportedBlendedMegatronDatasetBuilder
    build_tokenizer = imported_build_tokenizer
    GPTDataset = ImportedGPTDataset
    GPTDatasetConfig = ImportedGPTDatasetConfig
    Split = ImportedSplit


@contextmanager
def rank_zero_when_distributed_is_not_initialized():
    if torch.distributed.is_initialized():
        yield
        return

    original_get_rank = torch.distributed.get_rank
    torch.distributed.get_rank = lambda *args, **kwargs: 0
    try:
        yield
    finally:
        torch.distributed.get_rank = original_get_rank


def build_tokenizer_for_replay(args: argparse.Namespace):
    tokenizer_args = SimpleNamespace(
        rank=0,
        tokenizer_type=args.tokenizer_type,
        tokenizer_model=args.tokenizer_model,
        vocab_file=None,
        merge_file=None,
        vocab_size=None,
        vocab_extra_ids=args.vocab_extra_ids,
        make_vocab_size_divisible_by=args.make_vocab_size_divisible_by,
        tensor_model_parallel_size=1,
        padded_vocab_size=None,
    )
    return build_tokenizer(tokenizer_args)


def get_iteration_range(args: argparse.Namespace) -> range:
    if args.iter_index is not None:
        if args.iter_index < 0:
            raise ValueError("--iter-index must be non-negative")
        start = args.iter_index
        end = args.iter_index + 1
    else:
        start = 0 if args.iter_start is None else args.iter_start
        end = args.train_iters if args.iter_end is None else args.iter_end

    if start < 0:
        raise ValueError("--iter-start must be non-negative")
    if end < start:
        raise ValueError("--iter-end must be greater than or equal to --iter-start")
    if end > args.train_iters:
        raise IndexError(
            f"requested iteration range exceeds training loop: end={end}, "
            f"total={args.train_iters}"
        )
    return range(start, end)


def get_blend_from_data_path(data_path: list[str]):
    if len(data_path) == 1:
        return [data_path[0]], None

    if len(data_path) % 2 != 0:
        raise ValueError(
            "--data-path must be either a single dataset path or weight-path pairs"
        )

    weights = []
    prefixes = []
    for weight_index in range(0, len(data_path), 2):
        weights.append(float(data_path[weight_index]))
        prefixes.append(data_path[weight_index + 1])
    return prefixes, weights


def build_train_dataset(args: argparse.Namespace):
    tokenizer = build_tokenizer_for_replay(args)
    config_kwargs = {
        "random_seed": args.seed,
        "sequence_length": args.seq_length,
        "blend": get_blend_from_data_path(args.data_path),
        "blend_per_split": [None, None, None],
        "split": args.split,
        "path_to_cache": args.data_cache_path,
        "mmap_bin_files": args.mmap_bin_files,
        "mock": False,
        "tokenizer": tokenizer,
        "reset_position_ids": False,
        "reset_attention_mask": False,
        "eod_mask_loss": False,
        "create_attention_mask": True,
    }
    accepted_config_kwargs = inspect.signature(GPTDatasetConfig).parameters
    config = GPTDatasetConfig(
        **{
            key: value
            for key, value in config_kwargs.items()
            if key in accepted_config_kwargs
        }
    )
    train_num_samples = args.train_iters * args.global_batch_size
    sizes = [train_num_samples, 0, 0]
    with rank_zero_when_distributed_is_not_initialized():
        train_ds, _, _ = BlendedMegatronDatasetBuilder(
            GPTDataset,
            sizes,
            lambda: True,
            config,
        ).build()
    if train_ds is None:
        raise RuntimeError("failed to build the train dataset")
    return train_ds, tokenizer


def get_dataset_paths_from_data_path(data_path: list[str]) -> list[str]:
    if len(data_path) == 1:
        return data_path

    if len(data_path) % 2 != 0:
        raise ValueError(
            "--data-path must be either a single dataset path or weight-path pairs"
        )

    dataset_paths = []
    for weight_index in range(0, len(data_path), 2):
        float(data_path[weight_index])
        dataset_paths.append(data_path[weight_index + 1])
    return dataset_paths


def get_global_batch_dataset_indices(
    args: argparse.Namespace,
    total_samples: int,
    iteration: int,
) -> list[int]:
    batch_start = iteration * args.global_batch_size
    if batch_start >= total_samples:
        raise IndexError(
            f"requested global batch exceeds dataset length: start={batch_start}, total={total_samples}"
        )
    batch_end = min(batch_start + args.global_batch_size, total_samples)
    return list(range(batch_start, batch_end))


def resolve_source_dataset_sample(
    dataset: Any,
    dataset_index: int,
    item: dict[str, Any],
) -> tuple[Any, int, int | None]:
    if hasattr(dataset, "datasets"):
        dataset_id = int(item.get("dataset_id", dataset.dataset_index[dataset_index]))
        dataset_sample_index = int(
            item.get("dataset_sample_index", dataset.dataset_sample_index[dataset_index])
        )
        return dataset.datasets[dataset_id], dataset_sample_index, dataset_id

    return dataset, dataset_index, None


def get_indexed_dataset_spans(
    source_dataset: Any,
    dataset_sample_index: int,
) -> list[dict[str, int]]:
    if not all(
        hasattr(source_dataset, attr)
        for attr in ("document_index", "sample_index", "shuffle_index", "dataset")
    ):
        return []

    shuffled_sample_index = int(source_dataset.shuffle_index[dataset_sample_index])
    doc_index_beg, doc_index_beg_offset = source_dataset.sample_index[shuffled_sample_index]
    doc_index_end, doc_index_end_offset = source_dataset.sample_index[shuffled_sample_index + 1]

    spans = []
    for doc_index in range(int(doc_index_beg), int(doc_index_end) + 1):
        document_id = int(source_dataset.document_index[doc_index])
        offset = 0 if doc_index > doc_index_beg else int(doc_index_beg_offset)
        if doc_index < doc_index_end:
            length = int(source_dataset.dataset.sequence_lengths[document_id]) - offset
        else:
            length = int(doc_index_end_offset) - offset + 1

        spans.append(
            {
                "document_id": document_id,
                "offset": offset,
                "length": length,
            }
        )

    return spans


def build_sample_record(
    dataset: Any,
    dataset_index: int,
    iteration: int,
    item: dict[str, Any],
    tokenizer: Any,
    dataset_paths: list[str],
) -> dict[str, Any]:
    token_ids = item["tokens"].tolist() + [int(item["labels"][-1])]
    record = {
        "iteration": iteration,
        "token_ids": token_ids,
        "text": tokenizer.detokenize(token_ids),
    }
    record["dataset_id"] = int(item.get("dataset_id", 0))
    if record["dataset_id"] < len(dataset_paths):
        record["dataset_path"] = dataset_paths[record["dataset_id"]]
    if hasattr(dataset, "dataset_sample_index"):
        record["dataset_sample_index"] = int(dataset.dataset_sample_index[dataset_index])
    else:
        record["dataset_sample_index"] = dataset_index

    source_dataset, source_sample_index, _source_dataset_id = resolve_source_dataset_sample(
        dataset,
        dataset_index,
        item,
    )
    indexed_dataset_spans = get_indexed_dataset_spans(source_dataset, source_sample_index)
    record["indexed_dataset_spans"] = indexed_dataset_spans
    if "dataset_path" not in record and hasattr(source_dataset, "dataset_path"):
        record["dataset_path"] = source_dataset.dataset_path
    return record


def iter_global_batch_records(
    args: argparse.Namespace,
    dataset: Any,
    tokenizer: Any,
    dataset_paths: list[str],
    iteration: int,
):
    dataset_indices = get_global_batch_dataset_indices(
        args,
        len(dataset),
        iteration,
    )
    for dataset_index in dataset_indices:
        item = dataset[dataset_index]
        yield build_sample_record(
            dataset,
            dataset_index,
            iteration,
            item,
            tokenizer,
            dataset_paths,
        )


def iter_output_payloads(args: argparse.Namespace):
    dataset, tokenizer = build_train_dataset(args)
    dataset_paths = get_dataset_paths_from_data_path(args.data_path)
    for iteration in get_iteration_range(args):
        yield from iter_global_batch_records(
            args,
            dataset,
            tokenizer,
            dataset_paths,
            iteration,
        )


class ProgressReporter:
    def __init__(self, total: int | None, interval_seconds: float, enabled: bool) -> None:
        self.total = total
        self.interval_seconds = interval_seconds
        self.enabled = enabled
        self.count = 0
        self.started_at = time.monotonic()
        self.last_report_at = self.started_at
        self.is_tty = sys.stderr.isatty()

    def update(self, increment: int = 1, force: bool = False) -> None:
        if not self.enabled:
            return
        self.count += increment
        now = time.monotonic()
        if not force and now - self.last_report_at < self.interval_seconds:
            return
        self.last_report_at = now
        elapsed = max(now - self.started_at, 1e-9)
        rate = self.count / elapsed
        if self.total:
            percent = min(100.0, 100.0 * self.count / self.total)
            message = (
                f"progress: {self.count:,}/{self.total:,} records "
                f"({percent:5.1f}%, {rate:,.1f} records/s)"
            )
        else:
            message = f"progress: {self.count:,} records ({rate:,.1f} records/s)"

        if self.is_tty:
            print(f"\r{message}", end="", file=sys.stderr, flush=True)
        else:
            print(message, file=sys.stderr, flush=True)

    def finish(self) -> None:
        if not self.enabled:
            return
        self.update(0, force=True)
        if self.is_tty:
            print(file=sys.stderr, flush=True)


def get_expected_output_records(args: argparse.Namespace) -> int:
    return len(get_iteration_range(args)) * args.global_batch_size


def resolve_output_path(output_path: str) -> Path:
    resolved = Path(output_path)
    if resolved.suffixes[-2:] != [".jsonl", ".gz"]:
        raise ValueError(f"--output must end with .jsonl.gz: {output_path}")
    if not resolved.is_absolute():
        resolved = (Path.cwd() / resolved).resolve()
    resolved.parent.mkdir(parents=True, exist_ok=True)
    return resolved


def write_output_serial(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    progress: ProgressReporter,
) -> None:
    resolved = resolve_output_path(output_path)
    with gzip.open(
        resolved,
        "wt",
        encoding="utf-8",
        compresslevel=gzip_compresslevel,
    ) as writer:
        for payload in payloads:
            writer.write(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
            writer.write("\n")
            progress.update()
    progress.finish()


def write_output_pipelined(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    output_queue_size: int,
    progress: ProgressReporter,
) -> None:
    resolved = resolve_output_path(output_path)
    sentinel = object()
    output_queue: queue.Queue[Any] = queue.Queue(maxsize=output_queue_size)
    writer_errors: list[BaseException] = []
    writer_failed = threading.Event()

    def writer_thread_main() -> None:
        try:
            with gzip.open(
                resolved,
                "wt",
                encoding="utf-8",
                compresslevel=gzip_compresslevel,
            ) as writer:
                while True:
                    payload = output_queue.get()
                    try:
                        if payload is sentinel:
                            return
                        writer.write(
                            json.dumps(
                                payload,
                                ensure_ascii=False,
                                separators=(",", ":"),
                            )
                        )
                        writer.write("\n")
                        progress.update()
                    finally:
                        output_queue.task_done()
        except BaseException as exc:
            writer_errors.append(exc)
            writer_failed.set()

    writer_thread = threading.Thread(
        target=writer_thread_main,
        name="replay-output-writer",
        daemon=True,
    )
    writer_thread.start()

    try:
        for payload in payloads:
            if writer_failed.is_set():
                raise writer_errors[0]
            while True:
                if writer_failed.is_set():
                    raise writer_errors[0]
                try:
                    output_queue.put(payload, timeout=0.1)
                    break
                except queue.Full:
                    continue
    finally:
        while True:
            try:
                output_queue.put(sentinel, timeout=0.1)
                break
            except queue.Full:
                if writer_failed.is_set():
                    break
        writer_thread.join()

    if writer_errors:
        raise writer_errors[0]
    progress.finish()


def write_output(
    payloads: Any,
    output_path: str,
    gzip_compresslevel: int,
    output_queue_size: int,
    progress: ProgressReporter,
) -> None:
    if output_queue_size <= 0:
        write_output_serial(payloads, output_path, gzip_compresslevel, progress)
        return
    write_output_pipelined(
        payloads,
        output_path,
        gzip_compresslevel,
        output_queue_size,
        progress,
    )


def main() -> None:
    args = parse_args()
    configure_megatron_imports(args.megatron_path)
    progress = ProgressReporter(
        total=get_expected_output_records(args),
        interval_seconds=args.progress_interval,
        enabled=args.progress,
    )
    write_output(
        iter_output_payloads(args),
        args.output,
        args.gzip_compresslevel,
        args.output_queue_size,
        progress,
    )


if __name__ == "__main__":
    main()
