#!/bin/bash
# Node-level training batch replay launcher.
#
# Environment variables:
# * ENV_DIR: Directory that contains scripts/environment.sh, venv, and src/Megatron-LM.
# * REPLAY_CONFIG: Optional shell config generated by extract_replay_config.py.

set -eu -o pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPLAY_CONFIG=${REPLAY_CONFIG:-}
if [[ -n "${REPLAY_CONFIG}" ]]; then
  source "${REPLAY_CONFIG}"
fi
ENV_DIR=${ENV_DIR:-$(pwd)}

source "${ENV_DIR}/scripts/environment.sh"
source "${ENV_DIR}/venv/bin/activate"

export LOGLEVEL=${LOGLEVEL:-INFO}
export PYTHONFAULTHANDLER=${PYTHONFAULTHANDLER:-1}

# Training data range to replay. Defaults to the whole training loop.
ITER_INDEX=${ITER_INDEX:-}
ITER_START=${ITER_START:-}
ITER_END=${ITER_END:-}

# Training config. Leave replay-critical values unset when they are not
# specified, so replay_training_batch.py can use Megatron-LM defaults or fail.
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-}
TRAIN_STEPS=${TRAIN_STEPS:-}
SEQ_LENGTH=${SEQ_LENGTH:-}
SEED=${SEED:-}

# Data config.
SPLIT=${SPLIT:-}
TOKENIZER_TYPE=${TOKENIZER_TYPE:-}
TOKENIZER_MODEL=${TOKENIZER_MODEL:-}
MAKE_VOCAB_SIZE_DIVISIBLE_BY=${MAKE_VOCAB_SIZE_DIVISIBLE_BY:-}
VOCAB_EXTRA_IDS=${VOCAB_EXTRA_IDS:-}
DATA_PATH=${DATA_PATH:-}
DATA_CACHE_PATH=${DATA_CACHE_PATH:-}
OUTPUT=${OUTPUT:-outputs/global-batches.jsonl.gz}
OUTPUT_QUEUE_SIZE=${OUTPUT_QUEUE_SIZE:-256}
GZIP_COMPRESSLEVEL=${GZIP_COMPRESSLEVEL:-9}
COMPRESS_WORKERS=${COMPRESS_WORKERS:-4}
COMPRESS_CHUNK_RECORDS=${COMPRESS_CHUNK_RECORDS:-256}
PROGRESS=${PROGRESS:-1}
PROGRESS_INTERVAL=${PROGRESS_INTERVAL:-5}
INCLUDE_TEXT=${INCLUDE_TEXT:-0}
READER_WORKERS=${READER_WORKERS:-8}
MEGATRON_PATH=${MEGATRON_PATH:-src/Megatron-LM}

mkdir -p "$(dirname "${OUTPUT}")"

ITER_RANGE_ARGS=()
if [[ -n "${ITER_INDEX}" ]]; then
  ITER_RANGE_ARGS=(--iter-index "${ITER_INDEX}")
else
  if [[ -n "${ITER_START}" ]]; then
    ITER_RANGE_ARGS+=(--iter-start "${ITER_START}")
  fi
  if [[ -n "${ITER_END}" ]]; then
    ITER_RANGE_ARGS+=(--iter-end "${ITER_END}")
  fi
fi

CONFIG_ARGS=()
if [[ -n "${REPLAY_CONFIG}" ]]; then
  CONFIG_ARGS=(--config "${REPLAY_CONFIG}")
fi

PROGRESS_ARGS=(--progress)
if [[ "${PROGRESS}" == "0" || "${PROGRESS}" == "false" || "${PROGRESS}" == "False" ]]; then
  PROGRESS_ARGS=(--no-progress)
fi

TEXT_ARGS=(--no-include-text)
if [[ "${INCLUDE_TEXT}" == "1" || "${INCLUDE_TEXT}" == "true" || "${INCLUDE_TEXT}" == "True" ]]; then
  TEXT_ARGS=(--include-text)
fi

EXTRA_REPLAY_ARGS=()
if [[ -n "${EXTRA_ARGS:-}" ]]; then
  # shellcheck disable=SC2206
  EXTRA_REPLAY_ARGS=(${EXTRA_ARGS})
fi

# shellcheck disable=SC2206
DATA_PATH_ARGS=(${DATA_PATH})

REPLAY_ARGS=(--megatron-path "${MEGATRON_PATH}")
if [[ -n "${GLOBAL_BATCH_SIZE}" ]]; then
  REPLAY_ARGS+=(--global-batch-size "${GLOBAL_BATCH_SIZE}")
fi
if [[ -n "${TRAIN_STEPS}" ]]; then
  REPLAY_ARGS+=(--train-iters "${TRAIN_STEPS}")
fi
if [[ -n "${SEQ_LENGTH}" ]]; then
  REPLAY_ARGS+=(--seq-length "${SEQ_LENGTH}")
fi
if [[ -n "${SEED}" ]]; then
  REPLAY_ARGS+=(--seed "${SEED}")
fi
if [[ -n "${TOKENIZER_TYPE}" ]]; then
  REPLAY_ARGS+=(--tokenizer-type "${TOKENIZER_TYPE}")
fi
if [[ -n "${TOKENIZER_MODEL}" ]]; then
  REPLAY_ARGS+=(--tokenizer-model "${TOKENIZER_MODEL}")
fi
if [[ -n "${MAKE_VOCAB_SIZE_DIVISIBLE_BY}" ]]; then
  REPLAY_ARGS+=(--make-vocab-size-divisible-by "${MAKE_VOCAB_SIZE_DIVISIBLE_BY}")
fi
if [[ -n "${VOCAB_EXTRA_IDS}" ]]; then
  REPLAY_ARGS+=(--vocab-extra-ids "${VOCAB_EXTRA_IDS}")
fi
if [[ ${#DATA_PATH_ARGS[@]} -gt 0 ]]; then
  REPLAY_ARGS+=(--data-path "${DATA_PATH_ARGS[@]}")
fi
if [[ -n "${DATA_CACHE_PATH}" ]]; then
  REPLAY_ARGS+=(--data-cache-path "${DATA_CACHE_PATH}")
fi
if [[ -n "${SPLIT}" ]]; then
  REPLAY_ARGS+=(--split "${SPLIT}")
fi

python "${SCRIPT_DIR}/replay_training_batch.py" \
  "${CONFIG_ARGS[@]}" \
  "${ITER_RANGE_ARGS[@]}" \
  "${REPLAY_ARGS[@]}" \
  --output "${OUTPUT}" \
  --output-queue-size "${OUTPUT_QUEUE_SIZE}" \
  --gzip-compresslevel "${GZIP_COMPRESSLEVEL}" \
  --compress-workers "${COMPRESS_WORKERS}" \
  --compress-chunk-records "${COMPRESS_CHUNK_RECORDS}" \
  "${PROGRESS_ARGS[@]}" \
  --progress-interval "${PROGRESS_INTERVAL}" \
  "${TEXT_ARGS[@]}" \
  --reader-workers "${READER_WORKERS}" \
  "${EXTRA_REPLAY_ARGS[@]}"

echo "Wrote replayed batch to ${OUTPUT}"
