offline_inference:
  prompt_json_path: []  # must be set
  output_base_dir: null
  exact_output_dir: null  # must be set

wandb:
  launch: false
  log: false
  entity: null
  project: null
  run_name: null

model:
  _target_: "vllm.LLM"
  model: null  # must be set
  dtype: "bfloat16"
  gpu_memory_utilization: 0.9
  tensor_parallel_size: 1

tokenizer:
  _target_: "transformers.AutoTokenizer.from_pretrained"
  pretrained_model_name_or_path: null  # must be set
  trust_remote_code: false
  use_fast: true

pipeline_kwargs:
  add_special_tokens: false

generator_kwargs:
  _target_: "vllm.SamplingParams"
  # top_p: 1.0
  # top_k: 0
  temperature: 0.0
  repetition_penalty: 1.0
